---
- name: VPC | Creating an AWS VPC inside mentioned Region
  connection: local
  ec2_vpc:
    region: "{{ vpc_region }}"
    state: present
    cidr_block: "{{ vpc_cidr_block }}"
    resource_tags: { "Name":"{{ vpc_name }}-vpc" }
    subnets: "{{ vpc_subnets }}" 
    internet_gateway: yes
    route_tables: "{{ public_subnet_rt }}"
  register: vpc

#- name: VPC | Write vpc id to file inside the state directory
#  shell: echo "{{ vpc.vpc_id }}" > "{{ vpc_name }}-vpc-info"
#  args:
#    chdir: aws/state/

#- name: VPC | Write public and private subnets id to files inside the state directory  
#  shell: echo "{{ item.id }}" > "{{ item.resource_tags.Name }}"
#  args:
#    chdir: aws/state/
#  with_items: "{{ vpc.subnets }}"

#- name: VPC | Set the public and private subnet id as facts
#  set_fact:
#    vpc_id: "{{ lookup('file', 'aws/state/' + vpc_name + '-vpc-info') }}"
#    public_subnet: "{{ lookup('file', 'aws/state/' + vpc_name + '-' + public_az + '-public-subnet') }}"
